/* 2023 - K2
All rights reserved. */

export enum RouteNames {
  BLOOM = 'bloom',
  SUNSET = 'sunset',
  SANDWICH = 'sandwich',
  VAPOR = 'vapor',
  // TESTER = 'tester',
  SASSIER = 'sassier',
  GEMINI = 'gemini',
  // GEMINIa = 'gemini',
  // GEMINIs = 'gemini',
  // GEMINIdf = 'gemini',
  // GEMINIasd = 'gemini',
  // GEMINIwe = 'gemini',
  // GEMINIasdv = 'gemini',
  // GEMINIhjk = 'gemini',
  // GEMINIoko = 'gemini',
  // GEMINIplpk = 'gemini',
  // GEMINIpkpk = 'gemini',
  // GEMINIret = 'gemini',
  // GEMINI3 = 'gemini',
  // GEMINIa4 = 'gemini',
  // GEMINIs5 = 'gemini',
  // GEMINIdf1 = 'gemini',
  // GEMINIasd1 = 'gemini',
  // GEMINI1we = 'gemini',
  // GEMIN1Iasdv = 'gemini',
  // GEMINI1hjk = 'gemini',
  // GEMINI1oko = 'gemini',
  // GEMINI1plpk = 'gemini',
  // GEMINI1pkpk = 'gemini',
  // GEMIN1Iret = 'gemini',
  // GEMI1NI = 'gemini',
  // GEMI1NIa = 'gemini',
  // GEMI1NIs = 'gemini',
  // GEMI1NIdf = 'gemini',
  // GEMI1NIasd = 'gemini',
  // GEMI1NIwe = 'gemini',
  // GEMI1NIasdv = 'gemini',
  // GEMI1NIhjk = 'gemini',
  // GEMI1NIoko = 'gemini',
  // GEMI1NIplpk = 'gemini',
  // GEMI1NIpkpk = 'gemini',
  // GEMI1NIret = 'gemini',
  // GEMI12NIret = 'gemini',
}
